# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Fly"
license = "MIT"
licenselink = "https://github.com/Sly777/fly/blob/master/LICENSE.md"
description = "Fly - Hugo Theme - created by Ilker Guller"
homepage = "http://siteforthistheme.com/"
tags = ["seo","travel","tachyons", "blog"]
features = ["blog"]
min_version = 0.19

[author]
  name = "Ilker Guller"
  homepage = "http://ilkerguller.com"
